repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: pytest-coverage
        name: Tests with 80% coverage
        entry: python -m pytest --cov=eoapi_notifier --cov-fail-under=80 --tb=short
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
