repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.11.7, loguru>=0.7.3, types-PyYAML]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: pytest-coverage
        name: Tests with coverage
        entry: uv run python -m pytest --ignore=tests/test_helm.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: helm-lint
        name: Helm lint
        entry: helm lint helm-chart/eoapi-notifier
        language: system
        files: ^helm-chart/
        pass_filenames: false

