# Default values for eoapi-notifier
replicaCount: 1

image:
  repository: ghcr.io/developmentseed/eoapi-notifier
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Application configuration
config:
  logLevel: INFO

  # Sources: Define where notifications come from
  sources:
    - type: pgstac
      config:
        # Database connection from existing Kubernetes secret
        connection:
          existingSecret:
            name: ""
            keys:
              username: "user"
              password: "password"
              host: "host"
              port: "port"
              database: "dbname"
        # Optional pgSTAC settings:
        # tables: ["items", "collections"]
        # min_connections: 1
        # max_connections: 10
        # enable_correlation: true

  # Outputs: Define where notifications are sent
  outputs:
    - type: mqtt
      config:
        broker_host: mqtt-broker
        broker_port: 1883
        # Optional: username, password, use_tls, topic, qos

    - type: cloudevents
      config:
        source: /eoapi/pgstac
        event_type: org.eoapi.stac.item
        # For KNative SinkBinding:
        destination:
          ref:
            apiVersion: messaging.knative.dev/v1
            kind: Broker
            name: my-channel-1
            namespace: serverless
        # For HTTP endpoints, use: endpoint: https://webhook.example.com

# Environment variables override config values with plugin prefixes
# Examples: PGSTAC_PASSWORD, MQTT_USERNAME, CLOUDEVENTS_ENDPOINT
# KNative: K_SINK automatically overrides CLOUDEVENTS_ENDPOINT
env: {}
