apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "eoapi-notifier.fullname" .}}
  labels:
    {{- include "eoapi-notifier.labels" . | nindent 4}}
data:
  config.yaml: |
    # eoAPI Notifier Configuration
    sources:
    {{- range .Values.config.sources}}
      - type: {{.type}}
        config:
        {{- if eq .type "postgres"}}
          host: {{.config.host}}
          port: {{.config.port}}
          database: {{.config.database}}
          {{- if $.Values.secrets.postgresql.create}}
          user: __POSTGRES_USERNAME__
          password: __POSTGRES_PASSWORD__
          {{- else}}
          username: {{.config.username}}
          password: {{.config.password}}
          {{- end}}
          {{- range $key, $value := .config}}
          {{- if not (or (eq $key "host") (eq $key "port") (eq $key "database") (eq $key "user") (eq $key "username") (eq $key "password"))}}
          {{$key}}: {{$value}}
          {{- end}}
          {{- end}}
        {{- else}}
          {{- toYaml .config | nindent 10}}
        {{- end}}
    {{- end}}

    outputs:
    {{- range .Values.config.outputs}}
      - type: {{.type}}
        config:
          {{- toYaml .config | nindent 10}}
    {{- end}}
