apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "eoapi-notifier.fullname" .}}
  labels:
    {{- include "eoapi-notifier.labels" . | nindent 4}}
data:
  config.yaml: |
    # eoAPI Notifier Configuration
    # Environment variables automatically override config values (e.g., HOST env var overrides host config)
    sources:
    {{- range .Values.config.sources}}
      - type: {{.type}}
        config:
          {{- if eq .type "pgstac"}}
          # Connection details provided via environment variables
          host: localhost
          port: 5432
          database: postgis
          user: postgres
          password: password
          {{- else}}
          {{- toYaml .config | nindent 10}}
          {{- end}}
    {{- end}}

    outputs:
    {{- range .Values.config.outputs}}
      - type: {{.type}}
        config:
          {{- if eq .type "cloudevents"}}
          {{- $config := omit .config "destination"}}
          {{- toYaml $config | nindent 10}}
          {{- else}}
          {{- toYaml .config | nindent 10}}
          {{- end}}
    {{- end}}
