apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "eoapi-notifier.fullname" .}}
  labels:
    {{- include "eoapi-notifier.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "eoapi-notifier.selectorLabels" . | nindent 6}}
  template:
    metadata:
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/configmap.yaml") . | sha256sum}}
        checksum/secret: {{include (print $.Template.BasePath "/secret-postgresql.yaml") . | sha256sum}}
      labels:
        {{- include "eoapi-notifier.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{include "eoapi-notifier.serviceAccountName" .}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}

      containers:
        - name: {{.Chart.Name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command:
            - "uv"
            - "run"
            - "eoapi-notifier"
          args:
            - "--log-level"
            - "{{.Values.config.logLevel}}"
            - "/app/config/config.yaml"
          env:
            - name: UV_CACHE_DIR
              value: "/tmp"
            {{- if .Values.secrets.postgresql.create }}
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "eoapi-notifier.fullname" . }}-postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eoapi-notifier.fullname" . }}-postgresql
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12}}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{include "eoapi-notifier.fullname" .}}
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.affinity}}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.tolerations}}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}
